In [4]:
from pathlib import Path


In [8]:
folder_path = Path("D:\\Github Repos\\StephenKing-GPT\\Data")
texts = []

In [9]:
for file in folder_path.glob("*.txt"):
    with open(file, "r", encoding="utf-8") as f:
        texts.append(f.read())

In [11]:
all_text = "\n".join(texts)

with open("D:\\Github Repos\\StephenKing-GPT\\Data\\input.txt", "w", encoding="utf-8") as f:
    f.write(all_text)

In [12]:
# read the file back to verify
with open("D:\\Github Repos\\StephenKing-GPT\\Data\\input.txt", "r", encoding="utf-8") as f:
    content = f.read()

In [13]:
print("Length of combined text:", len(content))

Length of combined text: 13625328


In [14]:
# first 500 characters
print(content[:500])

To an extent this novel deals with the legal aspects of child custody in the State of Maine I asked for help in understanding this subject from my friend Warren Silver who is a fine attorney Warren guided me carefully and along the way he also told me about a quaint old device called the Stenomask which I immediately appropriated for my own fell purposes If Ive made procedural mistakes in the story which follows blame me not my legal resource Warren also asked merather plaintively if I could may


In [20]:
# what are all the unique characters in the text?
chars = sorted(list(set(content)))
chars.append("!")
chars.append("?")
chars.append(".")
chars.append(",")
vocab_size = len(chars)
print("Unique characters:", chars)
print("Vocabulary size:", vocab_size)

Unique characters: ['\n', ' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '!', '?', '.', ',']
Vocabulary size: 58


In [21]:
string_to_int = {ch: i for i, ch in enumerate(chars)} # create a mapping from characters to integers
int_to_string = {i: ch for i, ch in enumerate(chars)} # create a mapping from integers to characters

print("String to integer mapping:", string_to_int)
print("Integer to string mapping:", int_to_string)


String to integer mapping: {'\n': 0, ' ': 1, 'A': 2, 'B': 3, 'C': 4, 'D': 5, 'E': 6, 'F': 7, 'G': 8, 'H': 9, 'I': 10, 'J': 11, 'K': 12, 'L': 13, 'M': 14, 'N': 15, 'O': 16, 'P': 17, 'Q': 18, 'R': 19, 'S': 20, 'T': 21, 'U': 22, 'V': 23, 'W': 24, 'X': 25, 'Y': 26, 'Z': 27, 'a': 28, 'b': 29, 'c': 30, 'd': 31, 'e': 32, 'f': 33, 'g': 34, 'h': 35, 'i': 36, 'j': 37, 'k': 38, 'l': 39, 'm': 40, 'n': 41, 'o': 42, 'p': 43, 'q': 44, 'r': 45, 's': 46, 't': 47, 'u': 48, 'v': 49, 'w': 50, 'x': 51, 'y': 52, 'z': 53, '!': 54, '?': 55, '.': 56, ',': 57}
Integer to string mapping: {0: '\n', 1: ' ', 2: 'A', 3: 'B', 4: 'C', 5: 'D', 6: 'E', 7: 'F', 8: 'G', 9: 'H', 10: 'I', 11: 'J', 12: 'K', 13: 'L', 14: 'M', 15: 'N', 16: 'O', 17: 'P', 18: 'Q', 19: 'R', 20: 'S', 21: 'T', 22: 'U', 23: 'V', 24: 'W', 25: 'X', 26: 'Y', 27: 'Z', 28: 'a', 29: 'b', 30: 'c', 31: 'd', 32: 'e', 33: 'f', 34: 'g', 35: 'h', 36: 'i', 37: 'j', 38: 'k', 39: 'l', 40: 'm', 41: 'n', 42: 'o', 43: 'p', 44: 'q', 45: 'r', 46: 's', 47: 't', 48: 'u',

In [22]:
def encode_string(s):
    return [string_to_int[ch] for ch in s]
def decode_string(l):
    return "".join([int_to_string[i] for i in l])

In [24]:
print(encode_string("Hello, world!"))

[9, 32, 39, 39, 42, 57, 1, 50, 42, 45, 39, 31, 54]


In [25]:
print(decode_string(encode_string("Hello, world!")))

Hello, world!


In [26]:
# convert to datatensor
import torch
data = torch.tensor(encode_string(content), dtype=torch.long)
print("Data tensor shape:", data.shape)
print("Data tensor dtype:", data.dtype)
print("First 100 elements of data tensor:", data[:100])

Data tensor shape: torch.Size([13625328])
Data tensor dtype: torch.int64
First 100 elements of data tensor: tensor([21, 42,  1, 28, 41,  1, 32, 51, 47, 32, 41, 47,  1, 47, 35, 36, 46,  1,
        41, 42, 49, 32, 39,  1, 31, 32, 28, 39, 46,  1, 50, 36, 47, 35,  1, 47,
        35, 32,  1, 39, 32, 34, 28, 39,  1, 28, 46, 43, 32, 30, 47, 46,  1, 42,
        33,  1, 30, 35, 36, 39, 31,  1, 30, 48, 46, 47, 42, 31, 52,  1, 36, 41,
         1, 47, 35, 32,  1, 20, 47, 28, 47, 32,  1, 42, 33,  1, 14, 28, 36, 41,
        32,  1, 10,  1, 28, 46, 38, 32, 31,  1])


In [27]:
#split the data into train and validation sets
n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]
print("Train data shape:", train_data.shape)
print("Validation data shape:", val_data.shape)

Train data shape: torch.Size([12262795])
Validation data shape: torch.Size([1362533])


In [28]:
context_length = 8
train_data[:context_length+1]

tensor([21, 42,  1, 28, 41,  1, 32, 51, 47])

In [30]:
x = train_data[:context_length]
y = train_data[1:context_length+1]

for t in range(context_length):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([21]) the target: 42
when input is tensor([21, 42]) the target: 1
when input is tensor([21, 42,  1]) the target: 28
when input is tensor([21, 42,  1, 28]) the target: 41
when input is tensor([21, 42,  1, 28, 41]) the target: 1
when input is tensor([21, 42,  1, 28, 41,  1]) the target: 32
when input is tensor([21, 42,  1, 28, 41,  1, 32]) the target: 51
when input is tensor([21, 42,  1, 28, 41,  1, 32, 51]) the target: 47


In [32]:
x

tensor([21, 42,  1, 28, 41,  1, 32, 51])

In [33]:
y

tensor([42,  1, 28, 41,  1, 32, 51, 47])

In [31]:
for t in range(context_length):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {decode_string(context.tolist())} the target: {decode_string([target.item()])}")

when input is T the target: o
when input is To the target:  
when input is To  the target: a
when input is To a the target: n
when input is To an the target:  
when input is To an  the target: e
when input is To an e the target: x
when input is To an ex the target: t


In [34]:
batch_size = 4 # how many sequences to process in parallel
context_length = 8 # how many characters are included in the context

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - context_length, (batch_size,))
    x = torch.stack([data[i:i+context_length] for i in ix])
    y = torch.stack([data[i+1:i+context_length+1] for i in ix])
    return x, y

In [35]:
xb, yb = get_batch("train")
print("Input batch shape:", xb.shape)
print("Target batch shape:", yb.shape)
print("Input batch:", xb)
print("Target batch:", yb)


Input batch shape: torch.Size([4, 8])
Target batch shape: torch.Size([4, 8])
Input batch: tensor([[35, 42, 50, 32, 45,  1, 47, 35],
        [32,  1, 35, 28, 31,  1, 30, 45],
        [ 1, 11, 42, 35, 41, 41, 52,  1],
        [ 1, 36, 47,  1, 41, 32, 49, 32]])
Target batch: tensor([[42, 50, 32, 45,  1, 47, 35, 32],
        [ 1, 35, 28, 31,  1, 30, 45, 36],
        [11, 42, 35, 41, 41, 52,  1, 45],
        [36, 47,  1, 41, 32, 49, 32, 45]])


In [36]:
#decode the first batch to verify
for i in range(batch_size):
    input_seq = decode_string(xb[i].tolist())
    target_seq = decode_string(yb[i].tolist())
    print(f"Input sequence: '{input_seq}' -> Target sequence: '{target_seq}'")

Input sequence: 'hower th' -> Target sequence: 'ower the'
Input sequence: 'e had cr' -> Target sequence: ' had cri'
Input sequence: ' Johnny ' -> Target sequence: 'Johnny r'
Input sequence: ' it neve' -> Target sequence: 'it never'


In [ ]:
# Modeling tomorrow!